<?php

// generate list of valid area codes

$ac = 200;

$valid_ac=array();

while ($ac <= 999)
{
	$url = 'http://localcallingguide.com/xmldialplan.php?npa='.$ac;
	$xml = file_get_contents($url);
	$data = simplexml_load_string($xml);

	if (!empty($data->dpdata->npa)) {
		$valid_ac[] = $ac;
	}
	$ac++;
}

$output='<'.'?php'."\n";
$output.='// generated by areacodes.php'."\n";
$output.='$valid_area_codes = '.var_export($valid_ac, true);

file_put_contents("valid_area_codes.php", $output);

