<?php

// generate list of valid area codes

$ac = 200;

$valid_ac=array();

while ($ac <= 999)
{
	$url = 'http://localcallingguide.com/xmldialplan.php?npa='.$ac;
	$xml = file_get_contents($url);
	$data = simplexml_load_string($xml);

	if (!empty($data->dpdata->npa)) {
		$valid_ac[] = $ac;
	}
	$ac++;
}

function store_var($var, $value)
{
	$output='<'.'?php'."\n";
	$output.='// generated by '.$_SERVER['PHP_SELF']."\n";
	$output.='$'.$var.' = '.var_export($value, true).";\n";
	file_put_contents($var.'.php', $output);
}

store_var('valid_area_codes', $valid_ac);

